// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAExz6LVZyD2P2zlLZreIywRprVFlMIvx8',
    appId: '1:558016742205:web:90b3f9ffeb9985ca71bb54',
    messagingSenderId: '558016742205',
    projectId: 'ecoleaker',
    authDomain: 'ecoleaker.firebaseapp.com',
    storageBucket: 'ecoleaker.firebasestorage.app',
    measurementId: 'G-ELGNXEMHSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4sz5Ml0ODSKnv55EjrQ3g4v1nidiJcRI',
    appId: '1:558016742205:android:d685b7c4609330fb71bb54',
    messagingSenderId: '558016742205',
    projectId: 'ecoleaker',
    storageBucket: 'ecoleaker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxzVXPEfypkEHWfM79Zk9cgKrBzOjuy_Q',
    appId: '1:558016742205:ios:9cff52d0ef0b323c71bb54',
    messagingSenderId: '558016742205',
    projectId: 'ecoleaker',
    storageBucket: 'ecoleaker.firebasestorage.app',
    iosBundleId: 'com.example.ecoleaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxzVXPEfypkEHWfM79Zk9cgKrBzOjuy_Q',
    appId: '1:558016742205:ios:9cff52d0ef0b323c71bb54',
    messagingSenderId: '558016742205',
    projectId: 'ecoleaker',
    storageBucket: 'ecoleaker.firebasestorage.app',
    iosBundleId: 'com.example.ecoleaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAExz6LVZyD2P2zlLZreIywRprVFlMIvx8',
    appId: '1:558016742205:web:1a9959f1a196128671bb54',
    messagingSenderId: '558016742205',
    projectId: 'ecoleaker',
    authDomain: 'ecoleaker.firebaseapp.com',
    storageBucket: 'ecoleaker.firebasestorage.app',
    measurementId: 'G-L4TVLDLEFC',
  );
}
